##
# Automatically approve and automerge Dependabot pull requests when conditions are met.
#
# This template will approve and set pull requests to automerge for all dependencies except python when the version bump is major or minor.
#
# - Dependabot only updates the Dockerfile when updating a Python dependency, so those pull requests require a little manual refinement.
# - Because this is an automerge, it will only merge pull requests where all the required checks pass.
#
# Adapted from https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#approve-a-pull-request
#
# Understand the security implications at https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
# before using this in a public repository where an untrusted user can fork it.
#
name: Automatically Merge Dependabot Updates
on:
  pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot_approve_boto3:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Info
      run: |
        echo 'steps.metadata.outputs.dependency-names:'
        echo '"${{ steps.metadata.outputs.dependency-names }}"'
        echo
        echo 'steps.metadata.outputs.dependency-type:'
        echo '"${{ steps.metadata.outputs.dependency-type }}"'
        echo
        echo 'steps.metadata.outputs.update-type:'
        echo '"${{ steps.metadata.outputs.update-type }}"'
        echo
        echo 'steps.metadata.outputs.updated-dependencies-json:'
        echo '"${{ steps.metadata.outputs.updated-dependencies-json }}"'
        echo
        echo 'toJSON(github.event.pull_request.labels):'
        echo '"${{ toJSON(github.event.pull_request.labels) }}"'
    - name: Approve
      # Approve unless the dependency name is python and the update-type is not semver-patch.
      if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' || ! contains(steps.metadata.outputs.dependency-names, 'python') }}
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Automerge
      if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' || ! contains(steps.metadata.outputs.dependency-names, 'python') }}
      # Automerge unless the dependency name is python and the update-type is not semver-patch.
      run: gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
