name: pre-commit-autoupdate

on:
  schedule:
  - cron: 12 6 * * 1
  workflow_dispatch:

jobs:
  pre-commit-autoupdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install pre-commit
    - run: pre-commit autoupdate
    - uses: peter-evans/create-pull-request@v3.12.1
      with:
        add-paths: .pre-commit-config.yaml
        commit-message: '[pre-commit] automatic update'
        title: '[pre-commit] automatic update'
        body: ''
